// Crawl a running preview build (next start) and write a static site for GitHub Pages.
// See docs/STATIC-PREVIEW.md.
import fs from "node:fs";
import path from "node:path";

const ORIGIN = process.env.PREVIEW_ORIGIN ?? "http://localhost:3200";
const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "/miti-home";
const REPO = process.cwd();
const OUT = path.join(REPO, "static-preview");

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// Public files and hashed build assets.
fs.cpSync(path.join(REPO, "public"), OUT, { recursive: true });
fs.cpSync(path.join(REPO, ".next-preview/static"), path.join(OUT, "_next/static"), { recursive: true });

const seeds = ["/", "/shop/", "/collections/", "/new/", "/best-sellers/", "/sale/", "/about/", "/contact/", "/gallery/",
  "/policies/", "/checkout/", "/account/", "/orders/", "/wishlist/"];
const skip = /^\/(admin|api|unsubscribe|reset-password|forgot-password|feeds|security\.txt|llms\.txt)/;
const queue = [...seeds];
const seen = new Set();
const failures = [];

function normalise(href) {
  if (!href.startsWith(BASE + "/") && href !== BASE) return null;
  let p = href.slice(BASE.length) || "/";
  p = p.split("#")[0].split("?")[0];
  if (!p.endsWith("/") && !path.extname(p)) p += "/";
  if (path.extname(p)) return null; // files are copied, not crawled
  return p;
}

while (queue.length) {
  const route = queue.shift();
  if (seen.has(route) || skip.test(route)) continue;
  seen.add(route);
  const res = await fetch(ORIGIN + BASE + route, { redirect: "manual" });
  if (res.status !== 200) { failures.push(`${res.status} ${route}`); continue; }
  const html = await res.text();
  const file = path.join(OUT, route, "index.html");
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, html);
  for (const m of html.matchAll(/href="([^"]+)"/g)) {
    const next = normalise(m[1].replace(/&amp;/g, "&"));
    if (next && !seen.has(next)) queue.push(next);
  }
}

// Branded 404 for unknown paths (GitHub Pages serves /404.html at the site root only,
// so keep a copy at the repo root of the published branch).
const notFound = await fetch(ORIGIN + BASE + "/this-page-does-not-exist/");
fs.writeFileSync(path.join(OUT, "404.html"), await notFound.text());

// Metadata files generated by route handlers.
for (const [route, name] of [["/sitemap.xml", "sitemap.xml"], ["/manifest.webmanifest", "manifest.webmanifest"], ["/icon.svg", "icon.svg"], ["/apple-icon.png", "apple-icon.png"], ["/favicon.ico", "favicon.ico"]]) {
  const r = await fetch(ORIGIN + BASE + route);
  if (r.ok) fs.writeFileSync(path.join(OUT, name), Buffer.from(await r.arrayBuffer()));
  else failures.push(`${r.status} ${route}`);
}
// Next serves the generated OG image and icons under hashed-ish routes; fetch any /miti-home/*.png|svg referenced in pages that is missing.
const missing = new Set();
for (const route of seen) {
  const f = path.join(OUT, route, "index.html");
  if (!fs.existsSync(f)) continue;
  for (const m of fs.readFileSync(f, "utf8").matchAll(/(?:src|href|content)="(\/miti-home\/[^"?#]+\.(?:png|jpe?g|webp|svg|ico|webmanifest|xml|txt))(?:\?[^"]*)?"/g)) {
    const rel = m[1].slice(BASE.length);
    if (!fs.existsSync(path.join(OUT, rel))) missing.add(rel);
  }
}
for (const rel of missing) {
  const r = await fetch(ORIGIN + BASE + rel);
  if (r.ok) { fs.mkdirSync(path.dirname(path.join(OUT, rel)), { recursive: true }); fs.writeFileSync(path.join(OUT, rel), Buffer.from(await r.arrayBuffer())); }
  else failures.push(`${r.status} asset ${rel}`);
}

fs.writeFileSync(path.join(OUT, ".nojekyll"), "");
console.log(JSON.stringify({ pages: seen.size - failures.filter((f) => !f.includes("asset")).length, fetchedAssets: missing.size, failures }, null, 1));
